ALTER TABLE jobs DROP CONSTRAINT jobs_kind_check;
ALTER TABLE jobs ADD CONSTRAINT jobs_kind_check CHECK(kind IN (
    'VERIFY_ARTIFACT','REBUILD_PROJECTION','FETCH_LAW_DETAIL','FETCH_SCOURT_DETAIL',
    'FETCH_SCOURT_INVENTORY'
));

ALTER TABLE manifests DROP CONSTRAINT manifests_kind_check;
ALTER TABLE manifests ADD CONSTRAINT manifests_kind_check CHECK(kind IN (
    'REGISTRY','DATASET','ASSET','IMPORT','DOCUMENT_OBSERVATION','INVENTORY_PAGES'
));
