ALTER TABLE jobs DROP CONSTRAINT jobs_kind_check;
ALTER TABLE jobs ADD CONSTRAINT jobs_kind_check CHECK(kind IN (
 'VERIFY_ARTIFACT','REBUILD_PROJECTION','FETCH_LAW_DETAIL','FETCH_SCOURT_DETAIL',
 'FETCH_SCOURT_INVENTORY','IMPORT_LEGACY_BUNDLE','ACQUIRE_IMAGE_BATCH',
 'STAGE_LEGACY_READER_BATCH','REFRESH_CURRENT_READER_IMAGES','ENRICH_CURRENT_LAWGO'
));
